pipeline {

	agent any

	tools {
        maven 'apache-maven-3.8.1' 
    }

	stages{

		stage ('teste'){

			steps {
				git 'https://github.com/gabrielgonoring/question-app-user-service.git'
				sh 'mvn package'
			}
		}
	}
}