pipeline {

	agent any

	tools {
        maven 'apache-maven-3.8.1' 
    }

	stages{

		stage ('empacotando'){

			steps {
				sh 'mvn package'
			}
		}

		stage ('fazendo deploy'){

			steps {
				sh 'java -jar target/*.jar'
			}
		
		}

	}
}